k8s-cfg refactor to enable --namespace --name
reworking options to include less dependence on mycfg

diff --git a/.k8s-cfg/functions b/.k8s-cfg/functions
--- a/.k8s-cfg/functions
+++ b/.k8s-cfg/functions
@@ -1,6 +1,6 @@
 #!/bin/bash
-# rename=0 # override in mycfg if renaming the components.
-# set -o errexit
+set -o errexit
+set -o functrace
 set -o nounset
 set -o pipefail
 # The next incarnation will use a git repo pulled into the
@@ -15,8 +15,35 @@ set -o pipefail
 #         /bin     # kubectl or other binaries
 #         /k8s     # yaml configs
 #         /scripts # this script and collections of other helpers
+
+function init
+{
+    local cfgdir=${dir}/.cfg
+    local mycfg=${cfgdir}/mycfg
+
+    if [[ ! -e ${mycfg:-} ]]; then
+        echo "${mycfg} was not found. have you tailored the configuration to your requirements?"
+        exit 3
+    fi
+    . ${mycfg}
+}
+
+function wrap-command
+{
+    local cfgdir=${dir}/.cfg
+    local k8scfgdir=$(readlink -f ${dir}/.k8s-cfg)
+    . ${k8scfgdir}/init
+   # . ${k8scfgdir}/flags
+   # . ${k8scfgdir}/mycfg
+   # eval ${@}
+    eval ${@}
+}
+
 function check
 {
+    export cfgdir=${dir}/.cfg
+    export k8scfgdir=$(readlink -f ${dir}/.k8s-cfg)
+    export k8scfgbin=$(readlink -f ${k8scfgdir}/../bin)
     if [[ ! ${dir:-} ]]; then
         echo "dir: variable not set"
         echo "A recipe in the script sourcing this file may work:"
@@ -24,43 +51,6 @@ function check
         exit 3
     fi
 }
-
-check
-
-export cfgdir=${dir}/.cfg
-export k8scfgdir=$(readlink -f ${dir}/.k8s-cfg)
-export k8scfgbin=$(readlink -f ${k8scfgdir}/../bin)
-
-mkdir -p ${k8scfgdir}  ${dir}/.private
-chmod 700 ${dir} ${k8scfgdir} ${dir}/.private ${cfgdir}
-
-if [[ ! -e ${k8scfgdir}/kubecfg ]]; then
-    echo "Unconfigured options in one of [.k8s-cfg/{kubecfg,options}]"
-    exit 3
-fi
-
-. ${k8scfgdir}/kubecfg
-# set default manipulation # inject secret like rsa pub key
-. ${k8scfgdir}/make-yaml
-
-if [[ -e ${make_yaml_file} || -L ${make_yaml_file} ]]; then
-    . ${make_yaml_file}
-else
-    cat <<EOF
-
-Required function make-yaml is not defined It's simplest form could be
-cat of the yaml file.
-
-Any function that dumps the yaml on stdout, such as a sed stream edit
-may also be used.
-
-override the default with options in .cfg/make-yaml, or 
-
-  ln -s ../.k8s-cfg/make-yaml .cfg/make-yaml
-
-EOF
-    exit 3
-fi
 
 function start
 {
@@ -78,38 +68,47 @@ EOF
 
 function status-all
 {
+    local k8scfgdir=${dir}/.k8s-cfg
+    . ${k8scfgdir}/init
     kubectl get --output=wide node
     kubectl get --all-namespaces --output=wide rc,pods,svc,ep
 }
 
 function status
 {
-    if (( rename )); then
-        local name=${id}${name}
-    fi
-    kubectl get --output=wide node
+    local k8scfgdir=${dir}/.k8s-cfg
+    local cfgdir=${dir}/.cfg
+    . ${k8scfgdir}/init
+    echo nodes
+    namespace-command kubectl get --output=wide node
     echo replication controllers
-    kubectl get --output=wide rc         ${name}             --namespace=${namespace}
+    namespace-command kubectl get --output=wide rc         ${name}        
     echo pods
-    kubectl get --output=wide po                             --namespace=${namespace}|head -1
-    kubectl get --output=wide po                             --namespace=${namespace}|grep ${name}
+    namespace-command kubectl get --output=wide po                        |head -1
+    namespace-command kubectl get --output=wide po                        |grep ${name}
     echo services
-    kubectl get --output=wide svc        ${name}             --namespace=${namespace}
+    namespace-command kubectl get --output=wide svc        ${name}        
     echo endpoints
-    kubectl get --output=wide ep         ${name}             --namespace=${namespace}
+    namespace-command kubectl get --output=wide ep         ${name}        
     echo secrets
-    kubectl get --output=wide secret     ${name}-secret      --namespace=${namespace}
+    namespace-command kubectl get --output=wide secret     ${name}-secret 
 }
 
 # --namespace=kube-system exec -it k8s-jenkins-ui-qfduo -c k8s-jump -- /bin/bash
 
 function generate
 {
+    local k8scfgdir=${dir}/.k8s-cfg
+    local cfgdir=${dir}/.cfg
+    . ${k8scfgdir}/init
+    # . ${k8scfgdir}/flags
+    # . ${cfgdir}/mycfg
+
     rm -f ${yaml}
     if (( debug )); then
         echo "building yaml file ${yaml} for debugging"
         if [[ ! -e ${yaml} ]]; then
-            make-yaml > ${yaml}
+            (make-yaml > ${yaml} )
         fi
         chmod 600 ${yaml}
     fi
@@ -117,11 +116,12 @@ function generate
 
 function git-config
 {
-    repo=${dir##*/}
-    if (( ! rename )) ; then
-        local id=""
-    fi
-    host=${id}k8s-git-repo
+    local k8scfgdir=${dir}/.k8s-cfg
+    . ${k8scfgdir}/init
+    . ${k8scfgdir}/flags
+
+    local repo=${dir##*/}
+    local host=${id}k8s-git-repo
 
     echo
     if [[ -e ${dir}/.git/config ]] && grep remote ${dir}/.git/config ; then
@@ -186,30 +186,41 @@ EOF
     git push --set-upstream github master
 }
 
+function namespace-command
+{
+    local k8scfgdir=${dir}/.k8s-cfg
+    local cfgdir=${dir}/.cfg
+    . ${k8scfgdir}/init
+    # . ${k8scfgdir}/flags
+    # . ${k8scfgdir}/kubecfg
+    # . ${cfgdir}/mycfg
+
+#    local namespace=$(namespace)
+    if [[ ! ${namespace:-} ]]; then
+        namespace=default
+    fi
+    local command="${@} --namespace=${namespace}"
+    if (( debug )) ; then
+        echo ${command}
+    fi
+    ${command}
+}
+
 function describe
 {
-    local namespace=$(make-yaml ${inyaml}|grep namespace:|grep -v '^ *#'|tail -1|cut -f 2 -d :)
-    namespace=${namespace// /}
-    if (( rename )) ; then
-        local name=${id}${name}
-    fi
-    if [[ ${namespace:-} ]]; then
-        kubectl describe --namespace=${namespace} po ${name}
-    else
-        kubectl describe po ${name}
-    fi
+    namespace-command kubectl describe po ${name}
 }
 
 function replicas
 {
-    if (( rename )); then
-        local name=${id}${name}
-    fi
-    kubectl scale --replicas=${1} rc/${name} --namespace=${name}
+    namespace-command kubectl scale --replicas=${1} rc/${name}
 }
 
 function push-image
 {
+    local k8scfgdir=${dir}/.k8s-cfg
+    . ${k8scfgdir}/init
+
     local image=${dir##*/}
     docker save ${image} > ${image}.tar
     for host in k8s-${id}master-01 k8s-${id}node-0{1..2}; do
@@ -222,69 +233,58 @@ function push-image
 
 function main
 {
+    # local k8scfgdir=${dir}/.k8s-cfg
+    # local flags=${k8scfgdir}/flags
+    # local init=${k8scfgdir}/init
+    # . ${k8scfgdir}/init
+    # . ${init}
+    # . ${flags}
+    # mkdir -p ${k8scfgdir}  ${dir}/.private
+    # chmod 700 ${dir} ${k8scfgdir} ${dir}/.private ${cfgdir}
+    local command=""
+    local count=""
     if (( $# )) ; then
-        # set flags prior to calling any methods
         for arg in ${@}; do
             case ${arg} in
-                --debug)
-                    debug=1
-                    ;;
-                --rename)
-                    rename=1
-                    ;;
-                --rename=*)
-                    rename=${arg##*=}
-                    if (( ${#rename} != 0 )); then
-                        rename=1
-                    fi
-                    ;;
-                --verbose)
-                    verbose=1
-                    ;;
-            esac
-        done
-        generate
-        for arg in ${@}; do
-            case ${arg} in
-                --debug|--verbose) # ignore these, don't generate a usage call
-                    ;;
-                --describe)
-                    describe
-                    ;;
-                --push-image)
-                    push-image
-                    ;;
-                --start)
-                    start
-                    ;;
-                --stop)
-                    stop
-                    ;;
-                --status)
-                    status
-                    ;;
-                --status-all)
-                    status-all
-                    ;;
-                --git-config)
-                    git-config
-                    ;;
-                --tunnel-start)
-                    tunnel-start
-                    ;;
-                --tunnel-stop)
-                    tunnel-stop
-                    ;;
-                --tunnel-status)
-                    tunnel-status
+                --debug|--verbose|--name=*|--namespace=*) # ignore these, don't generate a usage call
                     ;;
                 --replicas=[0-9]*)
-                    c=${arg##*=}
-                    replicas ${c}
+                    count=${arg##*=}
+                    command="replicas ${c}"
                     ;;
                 --replicas)
                     printf "\n${0##*/} --replicas requires an number of replicas to scale\n"
                     usage
+                    ;;
+                --describe)
+                    command=describe
+                    ;;
+                --push-image)
+                    command=push-image
+                    ;;
+                --start)
+                    command=start
+                    ;;
+                --stop)
+                    command=stop
+                    ;;
+                --status)
+                    command=status
+                    ;;
+                --status-all)
+                    command=status-all
+                    ;;
+                --git-config)
+                    command=git-config
+                    ;;
+                --tunnel-start)
+                    command=tunnel-start
+                    ;;
+                --tunnel-stop)
+                    command=tunnel-stop
+                    ;;
+                --tunnel-status)
+                    command=tunnel-status
                     ;;
                 *)
                     usage
@@ -293,24 +293,13 @@ function main
     else
         usage
     fi
-#    exit
+
+    if [[ ${command:-} ]]; then
+        generate ${@}
+        wrap-command ${command}
+    fi
 }
-
-if [[ -e ${k8scfgdir}/usage ]]; then
-    . ${k8scfgdir}/usage
-fi
-
-if [[ -e ${cfgdir}/usage ]]; then
-    . ${cfgdir}/usage
-fi
-
-if [[ -e ${k8scfgdir}/tunnel ]]; then
-    . ${k8scfgdir}/tunnel
-fi
-
-export namespace=$(namespace)
-
-if [[ -e ${cfgdir}/overrides ]]; then
-    . ${cfgdir}/overrides
-fi
+export K8S_ARGV=${@}
+# init
+check
 
